# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Team.create(name: 'New Jersey Devils', team_id: 1, division: 0, slug: 'devils')
Team.create(name: 'New York Islanders', team_id: 2, division: 0, slug: 'islanders')
Team.create(name: 'New York Rangers', team_id: 3, division: 0, slug: 'rangers')
Team.create(name: 'Philadelphia Flyers', team_id: 4, division: 0, slug: 'flyers')
Team.create(name: 'Pittsburgh Penguins', team_id: 5, division: 0, slug: 'penguins')
Team.create(name: 'Boston Bruins', team_id: 6, division: 1, slug: 'bruins')
Team.create(name: 'Buffalo Sabres', team_id: 7, division: 1, slug: 'sabres')
Team.create(name: 'Montreal Canadiens', team_id: 8, division: 1, slug: 'canadiens')
Team.create(name: 'Ottawa Senators', team_id: 9, division: 1, slug: 'senators')
Team.create(name: 'Toronto Maple Leafs', team_id: 10, division: 1, slug: 'leafs')
Team.create(name: 'Carolina Hurricanes', team_id: 12, division: 0, slug: 'hurricanes')
Team.create(name: 'Florida Panthers', team_id: 13, division: 1, slug: 'panthers')
Team.create(name: 'Tampa Bay Lightning', team_id: 14, division: 1, slug: 'lightning')
Team.create(name: 'Washington Capitals', team_id: 15, division: 0, slug: 'capitals')
Team.create(name: 'Chicago Blackhawks', team_id: 16, division: 2, slug: 'blackhawks')
Team.create(name: 'Detroit Red Wings', team_id: 17, division: 1, slug: 'wings')
Team.create(name: 'Nashville Predators', team_id: 18, division: 2, slug: 'predators')
Team.create(name: 'St. Louis Blues', team_id: 19, division: 2, slug: 'blues')
Team.create(name: 'Calgary Flames', team_id: 20, division: 3, slug: 'flames')
Team.create(name: 'Colorado Avalanche', team_id: 21, division: 2, slug: 'avalanche')
Team.create(name: 'Edmonton Oilers', team_id: 22, division: 3, slug: 'oilers')
Team.create(name: 'Vancouver Canucks', team_id: 23, division: 3, slug: 'canucks')
Team.create(name: 'Anaheim Ducks', team_id: 24, division: 3, slug: 'ducks')
Team.create(name: 'Dallas Stars', team_id: 25, division: 2, slug: 'stars')
Team.create(name: 'Los Angeles Kings', team_id: 26, division: 2, slug: 'kings')
Team.create(name: 'San Jose Sharks', team_id: 28, division: 2, slug: 'sharks')
Team.create(name: 'Columbus Blue Jackets', team_id: 29, division: 0, slug: 'jackets')
Team.create(name: 'Minnesota Wild', team_id: 31, division: 3, slug: 'wild')
Team.create(name: 'Winnipeg Jets', team_id: 33, division: 3, slug: 'jets')
Team.create(name: 'Arizona Coyotes', team_id: 53, division: 2, slug: 'coyotes')
Team.create(name: 'Las Vegas Golden Knights', team_id: 54, division: 2, slug: 'knights')
